// Regenerates src/lib/chain/abi.ts from the Foundry build (contracts/out).
// Usage: cd contracts && forge build && cd ../app && npm run gen:abi
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const CONTRACTS = ["HumanRegistry", "PermissionRegistry", "ValidationReceipts", "PenaltyLedger"];
const out = new URL("../../contracts/out/", import.meta.url);

let ts = "// Generated by scripts/gen-abi.mjs from contracts/out. Do not edit by hand.\n";
for (const name of CONTRACTS) {
  const { abi } = JSON.parse(readFileSync(new URL(`${name}.sol/${name}.json`, out), "utf8"));
  ts += `\nexport const ${name[0].toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
mkdirSync(new URL("../src/lib/chain/", import.meta.url), { recursive: true });
writeFileSync(new URL("../src/lib/chain/abi.ts", import.meta.url), ts);
console.log(`wrote src/lib/chain/abi.ts (${CONTRACTS.join(", ")})`);
